import Link from "next/link";

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-[#0a0a0a] text-white">

      {/* Navbar */}
      <nav className="flex items-center justify-between px-8 py-5 border-b border-white/10">
        <Link href="/" className="text-xl font-bold tracking-tight">
          Assign<span className="text-violet-400">Mate</span>
        </Link>
        <Link href="/register" className="text-sm bg-violet-600 hover:bg-violet-500 px-4 py-2 rounded-lg transition">
          Get Started
        </Link>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-white/40 text-sm mb-12">Last updated: June 2025</p>

        <div className="flex flex-col gap-10 text-white/70 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By creating an account and using AssignMate, you agree to these Terms of Service. If you do not agree, please do not use our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">2. What AssignMate Does</h2>
            <p>AssignMate is an AI-powered tool that helps students generate assignment content. It is meant to be used as a learning aid and reference tool — not as a replacement for your own understanding and effort.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">3. Your Responsibilities</h2>
            <ul className="list-none flex flex-col gap-2 mt-3">
              {[
                "You are responsible for how you use the generated content",
                "You must comply with your institution's academic integrity policies",
                "You must not use AssignMate for any illegal or harmful purposes",
                "You must provide accurate information when registering",
                "You must keep your account credentials secure",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-violet-400 mt-1">→</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">4. Academic Integrity</h2>
            <p>AssignMate provides AI-generated content as a reference and learning tool. We strongly encourage students to use the generated content responsibly and in accordance with their institution's policies. We are not responsible for any academic consequences resulting from misuse of our service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">5. Plans and Payments</h2>
            <ul className="list-none flex flex-col gap-2 mt-3">
              {[
                "Free plan users get 5 generations per month",
                "Pro plan users get unlimited generations for Rs 500/month",
                "Payments are processed manually via JazzCash",
                "Refunds are handled on a case by case basis — contact us within 24 hours",
                "We reserve the right to change pricing with prior notice",
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-violet-400 mt-1">→</span>
                  {item}
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">6. Intellectual Property</h2>
            <p>The content generated by AssignMate belongs to you. However, we reserve the right to use anonymized data to improve our AI models. AssignMate's design, code, and branding are our intellectual property.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">7. Limitation of Liability</h2>
            <p>AssignMate is provided "as is" without warranties of any kind. We are not liable for any academic, financial, or other damages resulting from the use of our service. AI-generated content may contain errors — always review before submitting.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">8. Account Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these terms. You may also delete your account at any time by contacting us.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">9. Changes to Terms</h2>
            <p>We may update these terms from time to time. Continued use of AssignMate after changes means you accept the new terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-white mb-3">10. Contact</h2>
            <p>For any questions about these terms contact us at:</p>
            <p className="mt-2 text-violet-400">safeysafo@gmail.com</p>
          </section>

        </div>
      </div>

      {/* Footer */}
      <footer className="border-t border-white/10 px-8 py-6 text-center text-white/30 text-sm">
        <div className="flex items-center justify-center gap-6">
          <Link href="/" className="hover:text-white transition">Home</Link>
          <Link href="/privacy" className="hover:text-white transition">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-white transition">Terms of Service</Link>
        </div>
        <p className="mt-3">© 2025 AssignMate. Built for students, by a student.</p>
      </footer>

    </main>
  );
}